In [3]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

'''
Yes, there is a difference in the data types of the variables `list_` and `array_list`. The variable `list_` is a regular Python list, while `array_list` is a NumPy
array.

To print the data types of both variables, you can use the `type()` function in Python. 
'''

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

'''
the data type of `list_` is `<class 'list'>`, while the data type of `array_list` is `<class 'numpy.ndarray'>`.
'''
pass

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [4]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [6]:
#Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

'''
Yes, there will be a difference in the data type of the elements present in `list_` and `array_list` after the change:

array_list = np.array(object=list_, dtype=int)

In the updated code, the `dtype` parameter is set to `int`, which specifies that the elements of the NumPy array should be of integer type.

To print the data types of each element in both `list_` and `array_list`, you can iterate over the elements and use the `type()` function. 
'''

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))

'''
When you run this code, it will output the data type of each element in `list_` and `array_list` after the change. The output will look like:

the data type of each element in `list_` remains as `<class 'str'>`, while the data type of each element in `array_list` becomes `<class 'numpy.int64'>` after the 
conversion to integer type using `dtype=int`.
'''
pass

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
'''
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
'''
pass

In [9]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Shape of num_array
print("Shape of num_array:", num_array.shape)

# Size of num_array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [11]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#Hint: [The size of the array will be 9 and the shape will be (3,3).]


import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
